In [3]:
# 25_01-Iris.py
from sklearn import datasets
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
iris = datasets.load_iris()
category = 3
dim = 4
x_train ,x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
y_train2 = tf.keras.utils.to_categorical(y_train, num_classes = (category))
y_test2 = tf.keras.utils.to_categorical(y_test, num_classes = (category))
print("x_train[:4]",x_train[:4])
print("y_train[:4]",y_train[:4])
print("y_train2[:4]",y_train2[:4])



(120, 4)
(120,)
(30, 4)
(30,)
x_train[:4] [[6.7 3.3 5.7 2.1]
 [5.7 3.8 1.7 0.3]
 [4.9 3.1 1.5 0.1]
 [4.8 3.  1.4 0.1]]
y_train[:4] [2 0 0 0]
y_train2[:4] [[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [2]:
# 25_02-IrisExcel.py
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

# 获取鸢尾花的数据
iris = datasets.load_diabetes()
print("iris.data.shape = ", iris.data.shape)
print("dir(iris) = ", dir(iris))
print("iris.target.shape = ", iris.target.shape)
try:
	print("iris.target_names = ", iris.target_names)
except:
	print("No iris.feature_names = ")
# import xlsxwriter
import pandas as pd
# 转换数据模式
try:
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
except:
    df = pd.DataFrame(iris.data, columns= ['Sepal Length(cm)', 'Sepal Width(cm)', 'Petal Length(cm)', 'Petal Width(cm)'])
df['target'] = iris.target

#print(df.head())
df.to_csv("iris.csv",sep ='\t')

writer = pd.ExcelWriter('iris.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='Sheet1')
# writer.save()
# AttributeError: 'XlsxWriter' object has no attribute 'save'. Did you mean: '_save'?
# 新版pandas中save方法已经被弃用，只用writer.close()保存即可
writer.close()


iris.data.shape =  (442, 10)
dir(iris) =  ['DESCR', 'data', 'data_filename', 'data_module', 'feature_names', 'frame', 'target', 'target_filename']
iris.target.shape =  (442,)
No iris.feature_names = 


In [4]:
# Iris-mlp-show
history = .fit(x_train, y_train2, 
    epochs=200, 
    batch_size=128)

NameError: name 'model' is not defined